### ISSUE TITLE
Add internal ingress

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#1]
`az containerapp compose -g test_cli -e test1`

with a docker-compose of 

````yaml
services:
  foo:
    image: TBD
    expose: 
      - "3000"
````

and an existing resource group `test_cli`

**Needs a container with an HTTP endpoint**
