### ISSUE TITLE
Map `cpus` from compose service to container/resources/cpu 

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#14]
With an docker compose file of 

````yaml
services:
  foo:
    image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    ports: 
      - "8080:80"
    cpus: 0.75
````

Set the containerapps configuration to the correct CPU resource configuration.

Add bounds checks for unsupported cpu configurations ( https://docs.microsoft.com/azure/container-apps/containers#configuration ).
