### ISSUE TITLE
Map environment and env_file from service to container/env

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#15]
With a docker compose file of 

````yaml
services:
  foo:
    image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    ports: 
      - "8080:80"
    env_file:
      - ./test.env
    environment:
      DEV: true
      LOCATION: "east"
      ENVIRONMENT_NAME:
````

and a `test.env` of 

```
RACK_ENV=development
LOCATION="west"
```

set the correct environment for the containerapp

ensure that `environment` overrides values from `env_file`

Related issues - https://github.com/smurawski/pycomposefile/issues/7 and https://github.com/smurawski/pycomposefile/issues/9

https://docs.microsoft.com/en-us/azure/container-apps/containers#configuration
https://github.com/compose-spec/compose-spec/blob/master/spec.md#env_file
