### ISSUE TITLE
Map service/entrypoint from compose to container/command in containerapps

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#16]
With a docker compose of:

````yaml
services:
  foo:
    image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    ports: 
      - "8080:80"
    entrypoint: echo "see me!"
````

The entrypoint can be combined with command and can be a string or list. 

https://docs.microsoft.com/azure/container-apps/containers#configuration
https://github.com/compose-spec/compose-spec/blob/master/spec.md#entrypoint
