### ISSUE TITLE
With a simple custom `command` in the compose file

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#2]
`az containerapp compose -g test_cli -e test1`

with a docker-compose of 

````yaml
services:
  foo:
    image: smurawski/printenv:latest
    command: echo "hello world"
````

and an existing resource group `test_cli`
