### ISSUE TITLE
Add external ingress (http)

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#4]
`az containerapp compose -g test_cli -e test1`

with a docker-compose of 

````yaml
services:
  foo:
    image: TBD
    ports: 8080:80
````

and an existing resource group `test_cli`
