### ISSUE TITLE
With existing containerapps environment

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#5]
`az containerapp compose -g test_cli -e test1`

with a docker-compose of 

````yaml
services:
  foo:
    image: smurawski/printenv:latest
````

and an existing resource group `test_cli` and an existing containerapps environment named `test1`
