### ISSUE TITLE
With list of command values

### ISSUE THREAD

**Issue by smurawski** [smurawski/azure-cli-extensions#7]
This will require modification to the command parsing (currently assumes a simple string)

`az containerapp compose -g test_cli -e test1`

with a docker-compose of 

````yaml
services:
  foo:
    image: smurawski/printenv:latest
    command:  ['echo', 'hello world']
````

and an existing resource group `test_cli`
